"""add study target_audience and pricing_hypothesis

Revision ID: 3900b8c81727
Revises: 99b3c3047dec
Create Date: 2026-08-26 00:20:08.779604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3900b8c81727'
down_revision: Union[str, Sequence[str], None] = '99b3c3047dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('studies', sa.Column('pricing_hypothesis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'pricing_hypothesis')
    op.drop_column('studies', 'target_audience')
    # ### end Alembic commands ###
