"""Phase 6: Initial schema (llm_requests, model_registry, businesses, personas)

Revision ID: cb7c7deda755
Revises: 
Create Date: 2026-08-22 03:00:30.094092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb7c7deda755'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_table('llm_requests',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('task', sa.Enum('PERSONA_GENERATION', 'PERSONA_REFINEMENT', 'PERSONA_VALIDATION', 'PERSONA_INTERVIEW', 'PERSONA_RESPONSE', 'EVIDENCE_EXTRACTION', 'EVIDENCE_CLASSIFICATION', 'MEMORY_RETRIEVAL', 'MEMORY_SUMMARIZATION', 'CONTRADICTION_CHECK', 'CRITIC', 'REPORT_GENERATION', 'STRUCTURED_OUTPUT', 'BROWSER_AGENT', 'TOOL_CALLING', 'EMERGENCY_FALLBACK', name='tasktype', native_enum=False), nullable=False),
    sa.Column('pool', sa.String(length=64), nullable=True),
    sa.Column('persona_id', sa.String(length=64), nullable=True, comment='nullable; no FK (failed generations must be loggable)'),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('routing_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='list of AttemptRecord as dict'),
    sa.Column('served_by_provider', sa.String(length=128), nullable=True),
    sa.Column('request_model', sa.String(length=256), nullable=True),
    sa.Column('response_model', sa.String(length=256), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('completion_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_llm_requests_conversation_id'), 'llm_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_requests_created_at'), 'llm_requests', ['created_at'], unique=False)
    op.create_index('ix_llm_requests_created_at_desc', 'llm_requests', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_llm_requests_persona_id'), 'llm_requests', ['persona_id'], unique=False)
    op.create_index('ix_llm_requests_provider_model', 'llm_requests', ['served_by_provider', 'request_model'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_json', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('reasoning_level', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('latency_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_model_name'), 'model_registry', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_registry_provider_name'), 'model_registry', ['provider_name'], unique=False)
    op.create_index('uq_model_registry_provider_model', 'model_registry', ['provider_name', 'model_name'], unique=True)
    op.create_table('personas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generation_model', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_business_id'), 'personas', ['business_id'], unique=False)
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_index(op.f('ix_personas_business_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index('uq_model_registry_provider_model', table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_provider_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_model_name'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index('ix_llm_requests_provider_model', table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_persona_id'), table_name='llm_requests')
    op.drop_index('ix_llm_requests_created_at_desc', table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_created_at'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_conversation_id'), table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
