"""add research_runs, evidence_sources, chunks and claims

Revision ID: f5e32fddb1b9
Revises: 3900b8c81727
Create Date: 2026-08-26 00:33:13.489844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'f5e32fddb1b9'
down_revision: Union[str, Sequence[str], None] = '3900b8c81727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(Vector(384), 'postgresql'), nullable=False),
    sa.Column('embedding_space', sa.String(length=64), nullable=False),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_chunks_embedding_space'), 'evidence_chunks', ['embedding_space'], unique=False)
    op.create_index(op.f('ix_evidence_chunks_source_id'), 'evidence_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_chunks_study_id'), 'evidence_chunks', ['study_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_evidence_chunks_embedding_hnsw ON evidence_chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )
    op.create_table('evidence_claims',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('supporting_chunk_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contradicting_source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claims_run_id'), 'evidence_claims', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_study_id'), 'evidence_claims', ['study_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_user_id'), 'evidence_claims', ['user_id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sources_content_hash'), 'evidence_sources', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_sources_run_id'), 'evidence_sources', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_study_id'), 'evidence_sources', ['study_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_user_id'), 'evidence_sources', ['user_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('queries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_study_id'), 'research_runs', ['study_id'], unique=False)
    op.create_index(op.f('ix_research_runs_user_id'), 'research_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_runs_user_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_study_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_evidence_sources_user_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_study_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_run_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_content_hash'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_evidence_claims_user_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_study_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_run_id'), table_name='evidence_claims')
    op.drop_table('evidence_claims')
    op.drop_index(op.f('ix_evidence_chunks_study_id'), table_name='evidence_chunks')
    op.drop_index(op.f('ix_evidence_chunks_source_id'), table_name='evidence_chunks')
    op.drop_index(op.f('ix_evidence_chunks_embedding_space'), table_name='evidence_chunks')
    op.drop_table('evidence_chunks')
    # ### end Alembic commands ###
